In [2]:
# Importamos NumPy
import numpy as np

In [83]:
# Función para obtener las características de un objeto
def funcFeatures(obj, name):

  dimension = obj.ndim
  tipo      = ''

  if (dimension == 0):
    tipo = 'escalar'
  elif (dimension == 1):
    tipo = 'vector'
  elif (dimension == 2):
    tipo = 'matriz'
  elif (dimension >= 3):
    tipo = 'tensor'

  print(' -------------------------------\n','Caracteríscas del objeto: ' + name, '\n\tTipo de objeto:\t', tipo, "\n\tValor/es:\t", obj, "\n\tShape:\t\t", obj.shape, "\n\tDimensión/ones:\t", obj.ndim)

In [81]:
# Definición de los objetos
obj01 = np.array(37)
obj02 = np.array([2, 3, 5, 7, 11])
obj03 = np.array([[2 , 3 , 5 , 7 , 11],
                  [13, 17, 19, 23, 29]])
obj04 = np.array([[[2 , 3 , 5 , 7 , 11],
                   [13, 17, 19, 23, 29]],
                  [[2 , 4 , 6 , 8 , 10],
                   [12, 14, 16, 18, 20]],
                  [[1 , 3 , 5 , 7 , 9 ],
                   [11, 13, 15, 17, 19]]])
obj05 = x = np.array([[0, 1],
                      [2, 3],
                      [4, 5],
                      [6, 7]])

In [85]:
# Obtención de las características de los objetos
funcFeatures(obj01, 'obj01')
print()
funcFeatures(obj02, 'obj02')
print()
funcFeatures(obj03, 'obj03')
print()
funcFeatures(obj04, 'obj04')
print()
funcFeatures(obj05, 'obj05 - original -')
print()
funcFeatures(obj05.reshape(8, 1), 'obj05 - reshape(8, 1) -')
print()
funcFeatures(obj05.reshape(2, 4), 'obj05 - reshape(2, 4) -')
print()
funcFeatures(obj05.reshape(2, 4), 'obj05 - reshape(2, 4) -')
print()
funcFeatures(obj05, 'obj05 - original -')
print()
funcFeatures(obj05.T, 'obj05 - traspuesta -')

 -------------------------------
 Caracteríscas del objeto: obj01 
	Tipo de objeto:	 escalar 
	Valor/es:	 37 
	Shape:		 () 
	Dimensión/ones:	 0

 -------------------------------
 Caracteríscas del objeto: obj02 
	Tipo de objeto:	 vector 
	Valor/es:	 [ 2  3  5  7 11] 
	Shape:		 (5,) 
	Dimensión/ones:	 1

 -------------------------------
 Caracteríscas del objeto: obj03 
	Tipo de objeto:	 matriz 
	Valor/es:	 [[ 2  3  5  7 11]
 [13 17 19 23 29]] 
	Shape:		 (2, 5) 
	Dimensión/ones:	 2

 -------------------------------
 Caracteríscas del objeto: obj04 
	Tipo de objeto:	 tensor 
	Valor/es:	 [[[ 2  3  5  7 11]
  [13 17 19 23 29]]

 [[ 2  4  6  8 10]
  [12 14 16 18 20]]

 [[ 1  3  5  7  9]
  [11 13 15 17 19]]] 
	Shape:		 (3, 2, 5) 
	Dimensión/ones:	 3

 -------------------------------
 Caracteríscas del objeto: obj05 - original - 
	Tipo de objeto:	 matriz 
	Valor/es:	 [[0 1]
 [2 3]
 [4 5]
 [6 7]] 
	Shape:		 (4, 2) 
	Dimensión/ones:	 2

 -------------------------------
 Caracteríscas del objeto